### ISSUE TITLE
FYI: apple developer documentation about flags (FSEventStreamEventFlags)

### ISSUE THREAD

**Issue by joachimmetz** [dlcowen/FSEventsParser#6]
Likely authoritative source of the flags: https://developer.apple.com/documentation/coreservices/1455361-fseventstreameventflags

**Comment by gc-nibrahim** [comment]
Excellent. Thank you. Yes. I have seen these flags previously and I referenced them extensively while testing. However, the flags in the authoritative source seem to be used for consumption of live streaming FSEvents not the on-disk structures.

**Comment by joachimmetz** [comment]
They are not the same but look highly similar based on the observations in http://nicoleibrahim.com/apple-fsevents-forensics/.

**Comment by gc-nibrahim** [comment]
Correct. The flags from http://nicoleibrahim.com/apple-fsevents-forensics/ refer to the on-disk structure which Apple does not have documentation for. They were determined through extensive testing in conjunction with Apple's documentation regarding flags for live streaming of FSEvents. Also refer to issue #2 .
Thanks.
