### ISSUE TITLE
signature is DLS not SLD

### ISSUE THREAD

**Issue by joachimmetz** [dlcowen/FSEventsParser#7]
the signature is likely DLS1 (seeing the byte order) which is likely short for disk log(ger) stream version 1
this matches information found in the apple system logs: https://discussions.apple.com/thread/1626732

**Comment by joachimmetz** [comment]
the byte order is derived from that of the other values in the format. It is very rare for data formats to have mixed byte order.

**Comment by gc-nibrahim** [comment]
Updated the script to reference DLS instead of SLD. Thanks for your input.
